# Created with YamlCreate.ps1 v2.4.1 $debug=QUSU.CRLF.5-1-19041-4717.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Piriform.Recuva
PackageVersion: 1.54.120
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
AppsAndFeaturesEntries:
- DisplayVersion: 1.54.120
Installers:
- Architecture: x64
  InstallerUrl: https://download.ccleaner.com/rcsetup154.exe
  InstallerSha256: DBF0895D886B428C8465EE57AEA56A7E7B6E4C003EFD04CA00D216A2D821EAC9
- Architecture: x86
  InstallerUrl: https://download.ccleaner.com/rcsetup154.exe
  InstallerSha256: DBF0895D886B428C8465EE57AEA56A7E7B6E4C003EFD04CA00D216A2D821EAC9
ManifestType: installer
ManifestVersion: 1.6.0
